### ISSUE TITLE
Can't render the form

### ISSUE THREAD

**Issue by Incremental92** [nocio/oc-formstore-plugin#10]
Hi, very interesting plugin, but even logged in, I can't access the form. It always ask me my mail...
1) Could you provide a form page sample ? or a tuto to make the proper page ?
2) is it possible to directly have the form without authentication ?
Thanks

**Comment by frthjf** [comment]
Hi, thanks for installing my plugin! 

I'm not sure I understand correctly, what do you mean by 'it always ask me my mail' - could you provide a screenshot of where you got stuck and perhaps your form setup? 

1. The way FormStore works is that it uses existing models, so you can use any model of your October installation as an example (e.g. Rainlab\Blog\Models\Post). The plugin documentation provides a few examples, let me know if there are parts that are unclear.
2. That is not possible and is not really the intention of the plugin. However, there are [many](https://octobercms.com/plugins?search=forms) existing plugins that allow you to add forms without authentication.

Hope that helps.

**Comment by frthjf** [comment]
Closing this for now, feel free to re-open if needed. Thanks

**Comment by Incremental92** [comment]
Hello,
I'm developping on Windows WinNMP with a Material Design template of the
store.
I'm registered as a registered User. You can see on the right : "My
profile" (not styled for MD)
The only thing I get is this email field and the button and I can't go
further.
1) Is it possible to by-pass this email step ?
2) is your plugin working with forms like the one of Watch & Learn ?
https://watch-learn.com/video-tutorials/making-websites-with-october-cms-part-12-repeater-field
Thanks

[image: image.png]

**Comment by frthjf** [comment]
> 1) Is it possible to by-pass this email step ? 

No, as I said, you should consider using alternative form plugins

> 2) is your plugin working with forms like the one of Watch & Learn ?

Yes, you can use any standard October backend form you like

I'm not familiar with this theme, it may be that it does not use the JavaScript Ajax framework.

**Comment by Incremental92** [comment]
Thanks,
to be more precise, for question 1) I was thinking if I modify your code,
not with a configuration parameter ?
It's not possible ?

**Comment by frthjf** [comment]
If you modify the plugin code it's surely possible. Would be a nice feature. If you are willing to implement that, I'd be happy to accept a Pull request.

**Comment by Incremental92** [comment]
I'd like to render this form in a page accessible to registered users.
Could you give me clues to localize the function to modify to take of this
email asking form ?
Thanks

**Comment by frthjf** [comment]
You can find instructions how to do this in the documentation [here](https://github.com/nocio/oc-formstore-plugin#custom-authentication-methods). Unfortunately, I can't provide extended support with more detailed instructions. If you need professional support for this plugin, please contact the folks at [hello@pageballoon.com](mailto:hello@pageballoon.com)

**Comment by Incremental92** [comment]
ok thanks a lot
