### ISSUE TITLE
Integrity constraint violation NOT NULL

### ISSUE THREAD

**Issue by rangrage** [nocio/oc-formstore-plugin#3]
"SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: nocio_formstore_submissions.treated (SQL: insert into "nocio_formstore_submissions" ("form_id", "submitter_id", "data_id", "data_type", "updated_at", "created_at") values (4, 1, 5, Lmh\Forms\Models\Test, 2018-02-22 15:31:40, 2018-02-22 15:31:40))" on line 664 of C:\xampp\htdocs\ocplugins\vendor\laravel\framework\src\Illuminate\Database\Connection.php

I keep getting this error. Not sure what I am missing?

**Comment by frthjf** [comment]
Thanks for reporting this! When exactly do you get this error? When you try to submit the form? In backend or frontend? 

It seems like an error in the mysql database configuration. What happens is that FormStore tries to create an entry in the table ``nocio_formstore_submissions`` with the field value ``treated``=``Null`` which is not allowed by the database scheme. 

It looks like you are on xampp, so it's not a production environment I suppose? If it's not production, can you open the database on which OctoberCMS is installed, e.g. with phpmyadmin or the mysql client and allow the ``treated`` field to be nullable:
```mysql
ALTER TABLE `nocio_formstore_submissions` CHANGE `treated` `treated` DATETIME NULL; 
```

**Comment by frthjf** [comment]
Also, can you check if all the fields in your model ``Lmh\Forms\Models\Test`` are nullable?

**Comment by rangrage** [comment]
Hi, this error was on the front-end when clicking the "Start" button. 

After making the `treated` field NULL I was able to start and submit the form. However, when I tried it on another model which has fields that are NOT NULL it gave the same SQL error for those fields. So it may be worth adding to the documentation that all the form fields need to be nullable. (unless I've missed that)

Another minor issue I've noticed is in the backend when viewing the Submitted forms, the Data ID is not showing the correct ID field. I assume it is showing the `id`  field from  **nocio_formstore_submissions** instead of showing the `data_id` field. All the data has been stored correctly in the database. 

Thanks for you assistance mate.

**Comment by frthjf** [comment]
Good catch, I've added it to the documentation, thanks. I'll also look into producing a better error message if fields are not nullable. The other minor issue should be a simple fix in the columns.yaml, feel free to send a pull request. Otherwise, I'll fix it soon.

**Comment by rangrage** [comment]
Sorry, I didn't explain that correctly. I think the issue may either be in the Model or the Controller. 

Here's an example: 
<img src="https://image.ibb.co/nr2StH/data.png" alt="data" border="0">

The data is blank, and the correct `data_id` in the DB is **7**

Please let me know once you've had a chance to look at it. Thanks

**Comment by frthjf** [comment]
Ok I see, can you open a new issue, it seems like a different problem. Thanks

**Comment by rangrage** [comment]
Okay sure, thanks for you assistance.

**Comment by frthjf** [comment]
@rangrage The upcoming version will address the issues you've pointed out. Thanks for your report.
