### ISSUE TITLE
Data fields in Submissions controller are blank

### ISSUE THREAD

**Issue by rangrage** [nocio/oc-formstore-plugin#4]
<img src="https://image.ibb.co/nr2StH/data.png" alt="data" border="0"> 

The `id` field in the **nocio_formstore_submitters** is "2" and the `data_id` field value is actually "7" so not sure if the problem is in the controller of the model. 

Thanks for your help.

**Comment by frthjf** [comment]
Fixed in f9d5814, thanks!

**Comment by rangrage** [comment]
Perfect. I've tested it, all is in order. Thanks for your support and such a wonderful plugin.
