### ISSUE TITLE
Submitted Status showing Draft

### ISSUE THREAD

**Issue by rangrage** [nocio/oc-formstore-plugin#5]
<img src="https://image.ibb.co/maEqVx/status.png" alt="status" border="0">

After submitting a form the status does not change.

**Comment by frthjf** [comment]
Do you mean it doesn't change via AJAX? When you refresh the page it should be updated

**Comment by rangrage** [comment]
I've refreshed the page and also ran `php artisan cache:clear` and tried on 2 different PC's.

**Comment by frthjf** [comment]
Thanks, I could reproduce the bug on PHP 7.1. It was caused by 7.1 changes to class constant visibility. I'll release the fix soon.

**Comment by rangrage** [comment]
Excellent! Thanks for the fix :)
