### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by LarryBarker** [nocio/oc-formstore-plugin#6]
I'm having some difficulty getting the form to display on the page. I have a basic model with 3 fields for testing purposes. I've added the manager component to the page, can successfully "login" to the page but when I click `start` I get this error:
![image](https://user-images.githubusercontent.com/28734844/48632538-c2ecfa00-e986-11e8-94f1-4cd33ff38bf8.png)

I added `protected $fillable = ['*']` to my model and am still getting the error. 

**UPDATE**
So I had fields on my model that were set to NOT NULL which causes problems when the AjaxController tries to create a new model instance. Anyhow, I took off those requirements in the DB and am now getting this error:
![image](https://user-images.githubusercontent.com/28734844/48633500-13655700-e989-11e8-8aee-79c564103026.png)

**UPDATE**

Ok, so I had a relation defined in the Stored Forms area that did not actually exist on my model. I deleted the relation and it looks like the form is working now. Sorry for the mixup.

**Comment by frthjf** [comment]
Glad that your issue has been resolved. Just a quick note, you should protect the primary key field from mass assignment, e.g. ``protected $guarded = ['id'];``. Otherwise rogue users can overwrite existing submissions.
