### ISSUE TITLE
Load custom form widgets

### ISSUE THREAD

**Issue by LarryBarker** [nocio/oc-formstore-plugin#7]
My form uses a formwidget from the [RainLab Location](https://github.com/rainlab/location-plugin) plugin and is throwing an error when I try to start a form submission:

![image](https://user-images.githubusercontent.com/28734844/50185038-55612000-02dc-11e9-9699-e2ad9761ea6a.png)

Do you have any thoughts?

**UPDATE**: So I dug a little deeper into the code and found the [`loadBackendFormWidgets()` method in AjaxController](https://github.com/nocio/oc-formstore-plugin/blob/408ec1d266e889c1b76a0e81a5cee7104ee95fa6/traits/AjaxController.php#L91). I tried adding the code to load the addressfinder widget:
```
...
            'RainLab\Location\FormWidgets\AddressFinder' => [
                'label' => 'AddressFinder',
                'code' => 'addressfinder'
            ]
...
```
and now am getting this error:
![image](https://user-images.githubusercontent.com/28734844/50185413-4dee4680-02dd-11e9-82b8-68000fc210cf.png)

Still not sure how to get around this. Any help is appreciated. Thank you.

**Comment by frthjf** [comment]
Hi @LarBearrr! Thanks for using the plugin. You're on the right track, the widget needs to be loaded and bound to the controller. The problem, however, seems to be that the location plugin calls $controller->formGetWidget [here](https://github.com/rainlab/location-plugin/blob/6360a319f1e1e3eff8b6a43e85bdfdf3f84fbb58/formwidgets/AddressFinder.php#L67) but FormStore's manager component does not implement such a function. I suspect that's a method that is implement in form controllers though I couldn't find it searching the docs. Can you find out where this formGetWidget methods is implement if you use the plugin normally? Maybe we could then integrate into the manager controller so the method calls does not fail.

**Comment by frthjf** [comment]
I think ``formGetWidget`` should return the formWidget that is being instantiated [here](https://github.com/nocio/oc-formstore-plugin/blob/408ec1d266e889c1b76a0e81a5cee7104ee95fa6/traits/AjaxController.php#L127). Try adding a ``formGetWidget`` method to the ajax controller trait that returns it (e.g. ``return $this->widget;`` and changing L127 to ``$this->widget = ...``)

**Comment by LarryBarker** [comment]
Thank's for the quick reply! Your suggestions were correct, with one additional modification. 

[L131 ](https://github.com/nocio/oc-formstore-plugin/blob/408ec1d266e889c1b76a0e81a5cee7104ee95fa6/traits/AjaxController.php#L131) will need to be changed to use `$this->widget` instead of `$formWidget` as well.

I'm not sure what it would take to implement, but it may be beneficial to allow users to extend the formwidgets used by the plugin from their own plugins. 

Thanks again for the help!

**Comment by frthjf** [comment]
Cool, glad it worked. Would you like to submit a pull request that changes it over to ``$this->widget``? 

I agree, an event to extend the widgets would be good. I guess it's best to insert an Event hook [here](https://github.com/nocio/oc-formstore-plugin/blob/408ec1d266e889c1b76a0e81a5cee7104ee95fa6/traits/AjaxController.php#L115) that receives the ``$widget`` array so that listeners can modify it:
```php
Event::fire('nocio.formstore.widgets', [$widgets, $this->alias]);
```

Users could then load custom widgets like this:
```php
Event::listen('nocio.formstore.widgets', function(&$widgets, $alias) {
   $widgets['RainLab\Location\FormWidgets\AddressFinder'] =[
       'label' => 'AddressFinder',
       'code' => 'addressfinder'
   ]
});
```

Let me know if you'd like to submit a pull request for that. Otherwise, I'll do it myself but it might take some time.

**Comment by LarryBarker** [comment]
Ok, so I've made the changes and am testing them. I am now seeing the following error:
![image](https://user-images.githubusercontent.com/28734844/50301817-f3c0c300-044d-11e9-94d6-8da98c3cfc45.png)

**Comment by frthjf** [comment]
Thanks for trying this! Alright, that means that the widgets array is passed in as value and not as reference for some reason. I reckon the reference is not passed because it's inside an array constructor ``[]``. Anyway, in that case, we can also make it work without reference passing:
```php
if ($additional_widgets = Event::fire('nocio.formstore.widgets', [$this->alias])) {
     $widgets = array_merge($widgets, $additional_widgets);       
}
```
Then you should be able to extend it like this:

```php
Event::listen('nocio.formstore.widgets', function($alias) {
   return ['RainLab\Location\FormWidgets\AddressFinder' => [
       'label' => 'AddressFinder',
       'code' => 'addressfinder'
   ]];
});
```

**Comment by LarryBarker** [comment]
Hm... back to the original error:
![image](https://user-images.githubusercontent.com/28734844/50304464-a0eb0980-0455-11e9-8a23-9ee4ddb90e3e.png)

**Comment by frthjf** [comment]
Right, it seems like the array merging is not working correctly. Can you verify that $additional_widgets revieves the event array and that it is being merged into $widgets correctly (basically like when you hand-coded it in)? You can use Exeptions to debug, something like ``raise Exception(json_encode($addtional_widgets))`` which should display a message (or just use a debugger).

**Comment by LarryBarker** [comment]
I don't think we're using Events properly. 
```
        if ($additional_widgets = Event::fire('nocio.formstore.widgets', [$this->alias])) {

            throw new Exception(json_encode($additonal_widgets));
            // $widgets = array_merge($widgets, $additional_widgets);
        };
```
Is saying that $additional_widgets is not defined.

I also added this to my Plugin.php boot() method:
```
        Event::listen('nocio.formstore.widgets', function ($alias) {
            
            debug('From fired event: ' . $alias);
            return $alias;

        });
```
And it doesn't seem like the alias is being passed back to the AjaxController. 

Do we need to pass the entire AjaxController object with Event::fire and then modify it using the listen?

**Comment by LarryBarker** [comment]
Ok, I think I have it. We do indeed need to pass the AjaxController from the Event::fire() method and then modify the object using the Event::listen() method in the plugin. So here's what I did:

1. Create a new public proprety $backendWidgets in the AjaxController and move the $widgets = [] from the loadBackendWidgets() method to the new property. 
```
public $backendWidgets = [
        'Backend\FormWidgets\DatePicker' => [
            'label' => 'Date picker',
            'code' => 'datepicker'
        ],
        'Backend\FormWidgets\RichEditor' => [
            'label' => 'Rich editor',
            'code' => 'richeditor'
        ],
        'Backend\FormWidgets\Relation' => [
            'label' => 'Relation',
            'code' => 'relation'
        ],
        'Backend\FormWidgets\MarkdownEditor' => [
            'label' => 'MarkdownEditor',
            'code' => 'markdown'
        ],
        // Custom file upload for frontend use
        'Nocio\FormStore\Widgets\FrontendFileUpload' => [
            'label' => 'FileUpload',
            'code' => 'fileupload'
        ]
    ];
```
2. Update the loadBackendFormWidgets() method as follows:
```
        Event::fire('nocio.formstore.widgets', [$this]);

        foreach ($this->backendWidgets as $className => $widgetInfo) {
            WidgetManager::instance()->registerFormWidget($className, $widgetInfo);
        }
```
3. Now in our plugin we can listen for the event, and merge our form widget array with the backendWidget array:
```
public function boot()
    {
        Event::listen('nocio.formstore.widgets', function ($ajaxController) {

            $formWidgets = [
                'RainLab\Location\FormWidgets\AddressFinder' => [
                    'label' => 'AddressFinder',
                    'code' => 'addressfinder'
                ]
            ];

            $ajaxController->backendWidgets = array_merge($formWidgets, $ajaxController->backendWidgets);
            
            return $ajaxController->backendWidgets;

        });
    }
```

You can see that the RainLab Location AddresFinder form widget is now available:
![image](https://user-images.githubusercontent.com/28734844/50308531-20caa100-0461-11e9-82a0-cc066b844b49.png)
![image](https://user-images.githubusercontent.com/28734844/50308547-2de79000-0461-11e9-9b8e-c8596d4b1439.png)

**Comment by LarryBarker** [comment]
#8

**Comment by frthjf** [comment]
> Is saying that $additional_widgets is not defined.

There's a typo in additonal, that's what's causing the error.

> And it doesn't seem like the alias is being passed back to the AjaxController.

I think it's because you don't pass ``$this->alias`` in (at least not in your PR).

> Do we need to pass the entire AjaxController object with Event::fire and then modify it using the listen?

No, that would be bad practice. Events should receive only what's in their scope otherwise you can easily have security problems because it's no longer clear what's being modified.

**Comment by frthjf** [comment]
> Ok, I think I have it. We do indeed need to pass the AjaxController from the Event::fire() method and then modify the object using the Event::listen() method in the plugin. 

Thanks for the PR! However, I don't think passing in the entire controller is good because it conceals what needs to be modified. It also escalates the power of the event because it can now be used mess with the authentication middleware etc.

**Comment by LarryBarker** [comment]
Fair enough. I'm not sure what needs to be done then. It is working if I pass the AjaxController through the event which will suffice for my needs for the time being. I'm definitely interesting in seeing how this can be done following better practices. 

I'm happy to test/implement any other ideas you may have.

**Comment by frthjf** [comment]
No worries, thanks for your work. Let me make some modifications to your code to make it less general and then you can test if it works. I'll probably get to it tomorrow.

**Comment by confettibird** [comment]
Hi @LarBearrr, I've just released a new plugin version that supports custom widgets and implements your changes. The trick was to prefix the $widget array with an & so that it was passed in as reference correctly. Have a look at the [plugin docs](https://octobercms.com/plugin/nocio-formstore) that now contains an example on how to active the custom plugin. Let me know if you any other issues. Thanks for reporting and testing!

**Comment by frthjf** [comment]
Hi @LarBearrr, I've just released a new plugin version that supports custom widgets and implements your changes. The trick was to prefix the $widget array with an & so that it was passed in as reference correctly. Have a look at the [plugin docs](https://octobercms.com/plugin/nocio-formstore) that now contains an example on how to active the custom plugin. Let me know if you any other issues. Thanks for reporting and testing!
